name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "*.py"
      - "*.toml"
      - "**/*.csv"

  pull_request:
    branches:
      - "main"
    paths:
      - "*.py"
      - "*.toml"
      - "**/*.csv"

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PAGES_PROJECTNAME: speedtestspeedtestanalysis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Run app
      run: uv run analysis.py

    - name: 🚢 Deploy to Cloudflare Pages
      id: cloudflare_pages_deploy
      uses: cloudflare/wrangler-action@v3.13.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy dist --project-name=${{ env.PAGES_PROJECTNAME }} --commit-dirty=true
    - name: 📖 Print deployment URL
      env:
        DEPLOYMENT_URL: ${{ steps.cloudflare_pages_deploy.outputs.deployment-url }}
      run: echo "### ✅ Deploy succeeded! ${{ env.DEPLOYMENT_URL }} 🌟" >> $GITHUB_STEP_SUMMARY
